### ISSUE TITLE
Nothing shows

### ISSUE THREAD

**Issue by K4N0** [K-4U/serverInfoViewer#2]
I see a sun that is shadowed over.
the server is up and running but i don't see the daylight, nightime feature. 
I also don't see any configs for it. exept for k4lib
I installed all 3 files on the server, k4lib, server query extender, and server info viewer.
Are any of these client only?
I didnt' install server query extender onto the client.

**Comment by K4N0** [comment]
technic launcher mojangsters modpack
I added it to this, testing it before i actually upload it.

**Comment by K-4U** [comment]
Server Info viewer is client only.
Server Query Extender is server only.

In your port forwarding, did you forward the UDP port for minecraft too?
It may just be that, if it isn't, i should probably have some logs.

**Comment by K4N0** [comment]
Yes UDP. I would post that info. The way it was worded made it seem as if the server needed both files and also Server Query Extender.

**Comment by K-4U** [comment]
What versions are you running? Because i think there was a glitch in SQE that didn't allow it to work..

Otherwise still waiting on the logs!

**Comment by K4N0** [comment]
It works great! sry, it was cause i added both files to the server.
I retested it on my test server and it works great!
i think they need make it more obvious what to add where.
Thanks and sry for the trouble
